name: Update FX rates (daily)

on:
  schedule:
    - cron: "12 2 * * *"   # daily 02:12 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch USD -> target rates and write rates.json
        run: |
          set -euo pipefail
          DATE="$(date -u +%F)"
          SYMBOLS="EUR,GBP,CAD,AUD,NZD,JPY,CNY,HKD,SGD,INR,MXN,BRL,ZAR,AED,SAR,CHF,DKK,NOK,SEK"
          curl -fsSL "https://api.exchangerate.host/latest?base=USD&symbols=${SYMBOLS}" -o resp.json
          jq -e '.rates and (.rates | type=="object")' resp.json >/dev/null
          jq --arg date "$DATE" '{asOf:$date, rates:.rates}' resp.json > rates.json
          echo "Wrote rates.json:" && cat rates.json

      - name: Commit changes if any
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: refresh FX rates"
          file_pattern: rates.json
